In [7]:
pip install numpy

     ---------------------------------------- 0.0/61.0 kB ? eta -:--:--
     ------------------------- ------------ 41.0/61.0 kB 653.6 kB/s eta 0:00:01
     -------------------------------------- 61.0/61.0 kB 651.3 kB/s eta 0:00:00
   ---------------------------------------- 0.0/15.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/15.8 MB ? eta -:--:--
   ---------------------------------------- 0.1/15.8 MB 1.4 MB/s eta 0:00:11
    --------------------------------------- 0.2/15.8 MB 1.6 MB/s eta 0:00:11
    --------------------------------------- 0.3/15.8 MB 1.4 MB/s eta 0:00:11
    --------------------------------------- 0.4/15.8 MB 1.6 MB/s eta 0:00:10
   - -------------------------------------- 0.4/15.8 MB 1.6 MB/s eta 0:00:10
   - -------------------------------------- 0.5/15.8 MB 1.7 MB/s eta 0:00:10
   - -------------------------------------- 0.6/15.8 MB 1.6 MB/s eta 0:00:10
   - -------------------------------------- 0.7/15.8 MB 1.7 MB/s eta 0:00:09
   -- ------

ERROR: Could not install packages due to an OSError: [WinError 2] The system cannot find the file specified: 'C:\\Python310\\Scripts\\f2py.exe' -> 'C:\\Python310\\Scripts\\f2py.exe.deleteme'


[notice] A new release of pip is available: 23.3.2 -> 24.0
[notice] To update, run: python.exe -m pip install --upgrade pip


In [8]:
import numpy as np

In [11]:
random_int_array = np.random.randint(1, 50,10)
random_int_array 

array([24, 14, 46, 48, 35, 26, 20, 33, 12, 29])

תרגיל 1

In [12]:
random_int_array.dtype

dtype('int32')

In [14]:
np.ndim(random_int_array)

1

In [15]:
random_int_array2 = np.random.randint(10, 100, size=(2,5))
random_int_array2

array([[23, 64, 99, 59, 23],
       [55, 52, 27, 18, 27]])

תרגיל 2

In [16]:
random_int_array2.shape

(2, 5)

In [ ]:
תרגיל 1

In [17]:
array = np.random.randint(1, 50,10)
np.mean(array)

15.7

In [19]:
array2 = np.random.randint(10, 100, size=(2,5))
print(array2)
array22 = np.random.randint(10, 100, size=(2,5))
print(array22)
ab = np.add(array2, array22)
np.mean(ab)

[[96 72 58 79 67]
 [61 52 69 72 92]]
[[28 20 44 84 41]
 [17 10 29 59 40]]


109.0

In [ ]:
תרגיל 3

In [21]:
array1 = np.random.randint(1, 100,20)
print(array1)
condition = array1>50
filtered_arr = array1[condition]
filtered_arr

[18 82 46  6 73  5 21 98 87 19  3 32 59 38 48  8 60 85 79 34]


array([82, 73, 98, 87, 59, 60, 85, 79])

In [ ]:
תרגיל 4

In [25]:
arr =[1,2,3,4,5,6,7,8,9,10]
np.random.shuffle(arr)
random_int = np.random.randint(1, 10)
arr[random_int]

2